[package]
name = "hane-syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hane-kernel = { path = "../hane-kernel" }
pest = "2.2.1"
pest_derive = "2.4.0"
